global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'

  - job_name: 'node'
    static_configs:
      - targets: ['front:5173', 'server:3000']