groups:
  - name: alerts
    rules:
      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes{name=~"projet-blog-.*"} > 1000000000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.name }}"
          
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total{name=~"projet-blog-.*"}[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.name }}" 