FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Le flag --host permet d'accéder à l'app depuis l'extérieur du conteneur
CMD ["npm", "run", "dev", "--", "--host"] 