FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

# Installation des dépendances incluant swagger-ui-express et swagger-jsdoc
RUN npm install && \
    npm install swagger-ui-express swagger-jsdoc && \
    npm install -g nodemon

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"] 